"""change col name

Revision ID: a2075c9b01ec
Revises: c649b5e012f7
Create Date: 2020-07-14 09:38:02.409612

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2075c9b01ec'
down_revision = 'c649b5e012f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'new_name',
        new_column_name='cool_name',
        existing_type=sa.String(),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'cool_name',
        new_column_name='new_name',
        existing_type=sa.String(),
        existing_nullable=True
    )
    # ### end Alembic commands ###
